export interface TestData {
  id: string;
  test: string;
  testCode: string;
  department: string;
  sampleType: string;
  type: string;
  price: string;
  interPretation: boolean;
}

export const testData: TestData[] = [
  {
    id: "L001",
    test: "Amylase",
    testCode: "AMY",
    department: "Biochemistry",
    sampleType: "Serum",
    type: "Diagnostic",
    price: "220",
    interPretation: true,
  },
  {
    id: "L002",
    test: "Biopsy - Histopathology",
    testCode: "BIOPSY",
    department: "Histopathology",
    sampleType: "Tissue",
    type: "Diagnostic",
    price: "1500",
    interPretation: true,
  },
  {
    id: "L003",
    test: "Complete Blood Count (CBC)",
    testCode: "CBC",
    department: "Hematology",
    sampleType: "Blood",
    type: "Diagnostic",
    price: "250",
    interPretation: false,
  },
  {
    id: "L004",
    test: "Dengue NS1 Antigen",
    testCode: "DEN-NS1",
    department: "Immunology",
    sampleType: "Serum",
    type: "Screening",
    price: "600",
    interPretation: false,
  },
  {
    id: "L005",
    test: "Erythrocyte Sedimentation Rate (ESR)",
    testCode: "ESR",
    department: "Hematology",
    sampleType: "Blood",
    type: "Screening",
    price: "150",
    interPretation: false,
  },
  {
    id: "L006",
    test: "Fine Needle Aspiration Cytology (FNAC)",
    testCode: "FNAC",
    department: "Cytology",
    sampleType: "Cells",
    type: "Diagnostic",
    price: "1200",
    interPretation: true,
  },
  {
    id: "L007",
    test: "Glucose - Fasting",
    testCode: "FBS",
    department: "Biochemistry",
    sampleType: "Plasma",
    type: "Screening",
    price: "180",
    interPretation: true,
  },
  {
    id: "L008",
    test: "HbA1c",
    testCode: "HBA1C",
    department: "Biochemistry",
    sampleType: "Blood",
    type: "Monitoring",
    price: "300",
    interPretation: true,
  },
  {
    id: "L009",
    test: "Iron Studies",
    testCode: "IRON",
    department: "Biochemistry",
    sampleType: "Serum",
    type: "Diagnostic",
    price: "300",
    interPretation: false,
  },
  {
    id: "L010",
    test: "Joint Fluid Analysis",
    testCode: "JFA",
    department: "Clinical Pathology",
    sampleType: "Synovial Fluid",
    type: "Diagnostic",
    price: "500",
    interPretation: true,
  },
  {
    id: "L011",
    test: "Kidney Function Test (KFT)",
    testCode: "KFT",
    department: "Biochemistry",
    sampleType: "Serum",
    type: "Diagnostic",
    price: "280",
    interPretation: true,
  },
  {
    id: "L012",
    test: "Liver Function Test (LFT)",
    testCode: "LFT",
    department: "Biochemistry",
    sampleType: "Serum",
    type: "Diagnostic",
    price: "320",
    interPretation: true,
  },
  {
    id: "L013",
    test: "Malaria Antigen",
    testCode: "MAL-AG",
    department: "Microbiology",
    sampleType: "Blood",
    type: "Screening",
    price: "350",
    interPretation: false,
  },
  {
    id: "L014",
    test: "Pap Smear",
    testCode: "PAP",
    department: "Cytology",
    sampleType: "Cervical Cells",
    type: "Diagnostic",
    price: "700",
    interPretation: true,
  },
  {
    id: "L015",
    test: "Pleural Fluid Analysis",
    testCode: "PFA",
    department: "Clinical Pathology",
    sampleType: "Pleural Fluid",
    type: "Diagnostic",
    price: "600",
    interPretation: true,
  },
  {
    id: "L016",
    test: "Prothrombin Time (PT/INR)",
    testCode: "PT",
    department: "Hematology",
    sampleType: "Plasma",
    type: "Diagnostic",
    price: "200",
    interPretation: false,
  },
  {
    id: "L017",
    test: "Sputum Culture & Sensitivity",
    testCode: "SPUT",
    department: "Microbiology",
    sampleType: "Sputum",
    type: "Diagnostic",
    price: "450",
    interPretation: false,
  },
  {
    id: "L018",
    test: "Thyroid Function Test (TFT)",
    testCode: "TFT",
    department: "Endocrinology",
    sampleType: "Serum",
    type: "Diagnostic",
    price: "400",
    interPretation: true,
  },
  {
    id: "L019",
    test: "Urine Routine & Microscopy",
    testCode: "URM",
    department: "Clinical Pathology",
    sampleType: "Urine",
    type: "Diagnostic",
    price: "200",
    interPretation: false,
  },
  {
    id: "L020",
    test: "Vitamin D (25-OH)",
    testCode: "VITD",
    department: "Endocrinology",
    sampleType: "Serum",
    type: "Screening",
    price: "450",
    interPretation: true,
  },
  {
    id: "L021",
    test: "Widal Test (Typhoid)",
    testCode: "WIDAL",
    department: "Microbiology",
    sampleType: "Serum",
    type: "Screening",
    price: "250",
    interPretation: false,
  },
  {
    id: "L022",
    test: "Zinc Level",
    testCode: "ZN",
    department: "Biochemistry",
    sampleType: "Serum",
    type: "Diagnostic",
    price: "300",
    interPretation: true,
  },
];
